"""Update published_date field

Revision ID: 0ba0efc5f062
Revises: b6180f665156
Create Date: 2026-03-28 20:01:34.029795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ba0efc5f062'
down_revision: Union[str, Sequence[str], None] = 'b6180f665156'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'published_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True,
               schema='main')
    op.create_unique_constraint(None, 'users', ['email'], schema='main')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', schema='main', type_='unique')
    op.alter_column('books', 'published_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               schema='main')
    # ### end Alembic commands ###
