"""add email field

Revision ID: cbda653d517e
Revises: 191b0e19911f
Create Date: 2026-03-28 18:26:58.930093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbda653d517e'
down_revision: Union[str, Sequence[str], None] = '191b0e19911f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True), schema='main')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email', schema='main')
    # ### end Alembic commands ###
